In [9]:
import pandas as pd
import numpy as np

In [10]:
df=pd.read_csv('/content/Churn_Modelling.csv')

In [11]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [12]:
df = df.drop(columns=['RowNumber', 'CustomerId', 'Surname'])

In [14]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [16]:
df.describe()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

In [19]:
df.shape

(10000, 11)

In [20]:
df.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [22]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2)

In [23]:
X_train.shape

(8000, 10)

In [24]:
Y_train.shape

(8000,)

In [25]:
X_test.shape

(2000, 10)

In [26]:
Y_test.shape

(2000,)

In [27]:
numerical_column=['CreditScore','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary']
categorical_column=['Geography','Gender']

In [28]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_column),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_column)
    ]
)

In [29]:
X_train = preprocessor.fit_transform(X_train)

In [30]:
X_test = preprocessor.transform(X_test)

In [31]:
X_train

array([[-0.0041881 , -0.18024312,  1.38147383, ...,  0.        ,
         0.        ,  1.        ],
       [-0.9431885 , -0.94221944, -1.39257001, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.86349403, -0.65647832, -1.04581453, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 1.44042791, -1.79944281,  1.03471835, ...,  1.        ,
         0.        ,  1.        ],
       [ 0.8729002 ,  1.53420361,  0.34120739, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.05863654,  1.7246977 ,  0.68796287, ...,  0.        ,
         0.        ,  1.        ]])

In [32]:
X_test

array([[-0.08673758,  0.01025096,  1.03471835, ...,  0.        ,
         1.        ,  0.        ],
       [-0.62330924,  0.20074504, -1.39257001, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.67684517, -0.08499608, -0.35230357, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 0.08868008,  0.29599208, -1.04581453, ...,  1.        ,
         1.        ,  0.        ],
       [-0.01450678, -0.56123128, -1.04581453, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.41887802, -0.56123128,  0.34120739, ...,  0.        ,
         1.        ,  0.        ]])

In [33]:
Y_train=np.array(Y_train)
Y_test=np.array(Y_test)

In [34]:
Y_train

array([0, 0, 0, ..., 0, 0, 1])

In [35]:
Y_test

array([1, 0, 0, ..., 1, 0, 0])

In [36]:
np.save('X_train.npy', X_train)

In [37]:
np.save('X_test.npy', X_test)

In [38]:
np.save('Y_train.npy', Y_train)

In [39]:
np.save('Y_test.npy', Y_test)

In [41]:
import joblib

joblib.dump(preprocessor, "preprocessor.pkl")

['preprocessor.pkl']